### ISSUE TITLE
Impossible to install flickrsync

### ISSUE THREAD

**Issue by ManuCart** [danchal/flickrsync#1]
````
sudo pip3 install flickrsync
````

````
Downloading/unpacking flickrsync
  Could not find a version that satisfies the requirement flickrsync (from versions: 0.1.0rc1, 0.1.0rc7, 0.1.0rc10, 0.1.0rc5, 0.1.0rc16, 0.1.0rc6, 0.1.0rc16, 0.1.0rc15, 0.1.0rc2, 0.1.0rc8, 0.1.0rc8, 0.1.0rc6, 0.1.0rc5, 0.1.0rc11, 0.1.0rc7, 0.1.0rc9, 0.1.0rc13, 0.1.0rc2, 0.1.0rc4, 0.1.0rc11, 0.1.0rc10, 0.1.0rc1, 0.1.0rc14, 0.1.0rc13, 0.1.0rc14, 0.1.0rc15, 0.1.0rc12, 0.1.0rc12, 0.1.0rc4, 0.1.0rc9)
Cleaning up...
No distributions matching the version for flickrsync
Storing debug log for failure in /root/.pip/pip.log
````

**Comment by danchal** [comment]
Hi ManuCart, thanks for the feedback.

I tested the install procedure using a clean ubuntu1604 vm, everything was ok (v0.1.0rc16 installed). Which OS and version are you using?

The issue could be due to the current version number of flickrsync being [pre-release](https://packaging.python.org/tutorials/distributing-packages/#pre-release-versioning), i.e, ending in **rcN**?
Could you try to install again using the [--pre](https://pip.pypa.io/en/stable/reference/pip_install/?highlight=pre#pre-release-versions) option, i.e.
`$ sudo pip3 install --pre flickrsync`

**Comment by ManuCart** [comment]
Hi danchal,
Thanks for your help
It's working with 
````sudo pip3 install --pre flickrsync````
